"""products tables creation

Revision ID: 85696f6713a4
Revises: 6f7e3c73fb56
Create Date: 2023-11-06 01:35:41.064252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85696f6713a4'
down_revision: Union[str, None] = '6f7e3c73fb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('product_image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('qty_in_stock', sa.Integer(), nullable=False),
    sa.Column('product_image', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variation_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['variation_id'], ['variation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_configuration',
    sa.Column('product_item_id', sa.Integer(), nullable=True),
    sa.Column('variation_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_item_id'], ['product_item.id'], ),
    sa.ForeignKeyConstraint(['variation_option_id'], ['variation_option.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_configuration')
    op.drop_table('variation_option')
    op.drop_table('product_item')
    op.drop_table('variation')
    op.drop_table('product')
    op.drop_table('product_category')
    # ### end Alembic commands ###
