"""Order models

Revision ID: ca93801b7537
Revises: d72c40f096f0
Create Date: 2023-11-14 21:16:09.324330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca93801b7537'
down_revision: Union[str, None] = 'd72c40f096f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('shipping_address', sa.Integer(), nullable=True),
    sa.Column('shipping_method', sa.Integer(), nullable=True),
    sa.Column('order_total', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_status'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['user_payment_method.id'], ),
    sa.ForeignKeyConstraint(['shipping_address'], ['address.id'], ),
    sa.ForeignKeyConstraint(['shipping_method'], ['shipping_method.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_order')
    op.drop_table('shipping_method')
    op.drop_table('order_status')
    # ### end Alembic commands ###
