"""Product and Product_item merge

Revision ID: e8bcd502b951
Revises: 06d5986e4bfe
Create Date: 2023-11-17 14:21:47.958282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8bcd502b951'
down_revision: Union[str, None] = '06d5986e4bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_item', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('product_item', sa.Column('name', sa.String(), nullable=False))
    op.add_column('product_item', sa.Column('description', sa.String(), nullable=False))
    op.create_foreign_key(None, 'product_item', 'product_category', ['category_id'], ['id'])
    op.drop_column('product_item', 'SKU')
    op.drop_column('product_item', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_item', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_item', sa.Column('SKU', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_item', type_='foreignkey')
    op.drop_column('product_item', 'description')
    op.drop_column('product_item', 'name')
    op.drop_column('product_item', 'category_id')
    # ### end Alembic commands ###
